### ISSUE TITLE
This library does not work with GoCD 18.3.0

### ISSUE THREAD

**Issue by standingb76** [gaqzi/py-gocd#21]
I am getting this exception, as though the headers are not being retrieved from the api. Another issue has been raise that speaks to 401 errors. The reason is that bool(response) is always False. 
 
 File "gocdAdmin.py", line 58, in <module>
    pipeGroups = getPipelines()
  File "gocdAdmin.py", line 17, in getPipelines
    data = gocdMan.pipelineGroups()
  File "./lib/gocdManage.py", line 39, in pipelineGroups
    return response.is_ok, response.body
  File "/Library/Python/2.7/site-packages/gocd/api/response.py", line 97, in payload
    if self.is_json:
  File "/Library/Python/2.7/site-packages/gocd/api/response.py", line 67, in is_json
    return (self.content_type.startswith('application/json') or
AttributeError: 'bool' object has no attribute 'startswith'

**Comment by vamsilella** [comment]
This library has to be modified.... but if some one who needs this working with gocd 18.3 you can use yagocd i have verified and its working...

also i recommend please update this library ref: yagocd

Reason is as its unauthenticated(even for correct credentials) and its status code is 401 using this module .... its not because of  bool(response) is always False.(as this comes later... i mean after authentication.)

**Comment by henriquegemignani** [comment]
With the shutdown of Snap-CI, I have no means to publish any new versions of this package. We'd need @gaqzi to setup something else for that.

I use this package myself at work, however I'm blocked from updating our Go Server instance due to some changes many versions ago breaking our Docker image.

**Comment by standingb76** [comment]
I appreciate the response, thanks guys.
