### ISSUE TITLE
Using gocd python library with correct credentials getting status code 401

### ISSUE THREAD

**Issue by vamsilella** [gaqzi/py-gocd#20]
i have a script using gocd python module to connect to goserver and get pipeline status, it was working fine on GOCD 16.x but when i upgraded to 18.3 it always throwing 401 with correct credentials. can you help me on this.

from gocd import Server
server_connection = Server("http://localhost:8153", user = "abc", password = "Enp1")
a = server_connection.pipeline("Test1")
b = a.history()
print b.status_code

**Comment by standingb76** [comment]
Seems like the actual exception is:
  File "gocdAdmin.py", line 58, in <module>
    pipeGroups = getPipelines()
  File "gocdAdmin.py", line 17, in getPipelines
    data = gocdMan.pipelineGroups()
  File "./lib/gocdManage.py", line 39, in pipelineGroups
    return response.is_ok, response.body
  File "/Library/Python/2.7/site-packages/gocd/api/response.py", line 97, in payload
    if self.is_json:
  File "/Library/Python/2.7/site-packages/gocd/api/response.py", line 67, in is_json
    return (self.content_type.startswith('application/json') or
AttributeError: 'bool' object has no attribute 'startswith'

When testing using your above code "bool(response)" is always false. That's why you get the 401. Is this project still in flux?

**Comment by vamsilella** [comment]
Well that is what i said :) 
 its not authenticated(401) though with correct credentials and hence its showing "bool(response)" is always false but not vice versa...

so this library has to be modified at authentication steps....

**Comment by standingb76** [comment]
Yeah, hopefully we can get some traction here.
